name: Prevent Unauthorized PR Merges to Main

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  restrict-main-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR creator is authorized
        run: |
          echo "Checking if PR creator is allowed..."

          # Set list of allowed usernames (case sensitive)
          ALLOWED_USERS="PreetiSingh114 another-reviewer"

          echo "PR created by: ${{ github.actor }}"

          if echo "$ALLOWED_USERS" | grep -wq "${{ github.actor }}"; then
            echo "✅ ${{ github.actor }} is authorized to create PRs to main."
          else
            echo "❌ ${{ github.actor }} is not allowed to create PRs to main."
            echo "This PR will be blocked."
            exit 1
          fi
