name: Deploy Laravel to Azure App Service

on:
  push:
    branches:
      - developer   # 👈 change to "developer" if you deploy that branch
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: tw-app-l-dev-cin-01   # 👈 replace with your Azure App Service name
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
